### ISSUE TITLE
Missing Batman

### ISSUE THREAD

**Issue by emrikol** [scottsweb/battenberg#1]
There is a distinct lack of Batman.

**Comment by emrikol** [comment]
![image](https://user-images.githubusercontent.com/3060583/31186622-26bb0d0e-a8fd-11e7-8245-87b0c27ebc9b.png)

**Comment by scottsweb** [comment]
Consulted with Robin, he seemed OK with it

![tumblr_m12ts1u5bk1r5ur0ho1_500](https://user-images.githubusercontent.com/411945/51120761-bb729180-180d-11e9-85bf-49114c677a27.gif)
